name: build draw.io to png

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SPA NDOE
        uses: Burnett01/actions-drawio@1.0
        with:
          src: draw.io/SPA-NODE.drawio
          dest: draw.io/SPA-NODE.png
      - name: ricequant fe arch 2019 
        uses: Burnett01/actions-drawio@1.0
        with:
          src: draw.io/ricequant-fe-arch-2019.drawio
          dest: draw.io/ricequant-fe-arch-2019.png
      - name: ricequant fe arch 2021 
        uses: Burnett01/actions-drawio@1.0
        with:
          src: draw.io/ricequant-fe-arch-2021.drawio
          dest: draw.io/ricequant-fe-arch-2021.png
      - name: rqthemes
        uses: Burnett01/actions-drawio@1.0
        with:
          src: draw.io/rqthemes.drawio
          dest: draw.io/rqthemes.png
      - name: Commit png
        run: |
          git config --global user.name 'anson09'
          git config --global user.email 'finalsong6@gmail.com'
          git add --all
          git commit -m "draw.io png auto generated"
          git push
